% ==========================================================================
% INTRO
%   - Calculate the directivity of the audio sound generated by a PAL using
%       the convolution directivity model (CDM)
% ==========================================================================
function dir = PalLineSrc_CDM(pal, phi, varargin)

    ip = inputParser();
    ip.addParameter('type', 'direct')
    % Normalize in decibels
    ip.addParameter('is_norm_dB', false)
    ip.parse(varargin{:});
    ip = ip.Results;

    switch ip.type
        % direct CDM
        case 'direct'
            dir = integral(@(phi_vsrc) DirectCDM(pal, phi, phi_vsrc), ...
                0, 2*pi, 'ArrayValued', true);
        % modified CDM taking into account of the aperture effects of audio sound
        case 'modified'
            dir = integral(@(phi_vsrc) ModifiedCDM(pal, phi, phi_vsrc), ...
                0, 2*pi, 'ArrayValued', true);
        % Westervelt directivity
        case 'Westervelt'
            dir = Westervelt(pal, phi, 0);
        otherwise
            error('Wrong convolution model!')
    end

    if ip.is_norm_dB
        dir = 20*log10(abs(dir));
        dir = dir - max(dir(:));
    end
end

function dir = Westervelt(pal, phi, phi_vsrc)
    dir = 1i*pal.absorp_coef ./ (pal.ultra_high.num - conj(pal.ultra_low.num) ...
        - pal.audio.num .* cos(phi-phi_vsrc));
end

function dir = DirectCDM(pal, phi, phi_vsrc)
    dir1 = pal.src_low.CalDirectivity(phi_vsrc);
    dir2 = pal.src_high.CalDirectivity(phi_vsrc);
    dir_westervelt = Westervelt(pal, phi, phi_vsrc);
    dir = dir_westervelt .* conj(dir1) .* dir2;
end

function dir = ModifiedCDM(pal, phi, phi_vsrc)
    dira = pal.src_audio.CalDirectivity(phi);
    dir = DirectCDM(pal, phi, phi_vsrc) .* dira;
end
