% ==========================================================================
% INTRO
%   - Calculate the directivity of the audio sound generated by a PAL using
%       the convolution directivity model (CDM)
% ==========================================================================
function [dir, dira] = PalLineSrc_CDM(pal, phi, varargin)

    ip = inputParser();
    ip.addParameter('type', 'direct')
    % Normalize in decibels
    ip.addParameter('is_norm_dB', false)
    ip.parse(varargin{:});
    ip = ip.Results;

    
    switch ip.type
        % direct CDM
        case 'direct'
            dira = nan;
            dir = integral(@(phi_vsrc) DirectCDM(pal, phi, phi_vsrc), ...
                0, 2*pi,...
                'ArrayValued', true);
        % improved CDM taking into account of the aperture effects of audio sound
        case 'improved'
            dira = pal.src_audio.CalDirectivity(phi);
            dir = integral(@(phi_vsrc) ImprovedCDM(pal, phi, phi_vsrc), ...
                0, 2*pi,...
                'ArrayValued', true);
        % Westervelt directivity
        case 'Westervelt'
            dir = pal.absorp_coef ...
                ./ (pal.ultra_high.num - conj(pal.ultra_low.num) ...
                - pal.audio.num .* cos(phi-pi/2));
        otherwise
            error('Wrong convolution model!')
    end

    if ip.is_norm_dB
        dir = 20*log10(abs(dir));
        dir = dir - max(dir(:));
    end
end

function dir = DirectCDM(pal, phi, phi_vsrc)
    dir1 = pal.src_low.CalDirectivity(phi_vsrc);
    dir2 = pal.src_high.CalDirectivity(phi_vsrc);
    di_westervelt = pal.absorp_coef ./ (pal.ultra_high.num - conj(pal.ultra_low.num) ...
        - pal.audio.num .* cos(phi-phi_vsrc));
    dir = di_westervelt .*conj(dir1) .* dir2;
end


function dir = ImprovedCDM(pal, phi, phi_vsrc)
    dira = pal.src_audio.CalDirectivity(phi);
    dir = DirectCDM(pal, phi, phi_vsrc) .* dira;
end
