% =========================================================================
% - Calculate the directivity of the audio sound generated by a PAL
%   using the 3D convolution directivity model (CDM)
% -------------------------------------------------------------------------
% INPUT
%   - pal: PAL wave info
%   - theta, phi: zenithal and azimuthal coordinates of field points
% =========================================================================
function dir = PalPlanarSrc_CDM(pal, fp, varargin)

    ip = inputParser();
    ip.addParameter('int_num', 2e2);
    ip.addParameter('is_norm_dB', true);
    ip.addParameter('type', 'direct')
    ip.parse(varargin{:});
    ip = ip.Results;

    [theta_vsrc, theta_vsrc_weight] = GaussLegendreQuadParam(ip.int_num, 0, pi, 'dim', 8);
    [phi_vsrc, phi_vsrc_weight] = GaussLegendreQuadParam(ip.int_num, 0, 2*pi, 'dim', 9);

    switch ip.type
        case 'direct'
            dir = sum(DirectCDM(pal, fp.theta, fp.phi, theta_vsrc, phi_vsrc) ...
                .* theta_vsrc_weight .* phi_vsrc_weight, [8,9]);
        case 'modified'
            dir = sum(ModifiedCDM(pal, fp.theta, fp.phi, theta_vsrc, phi_vsrc)...
                .* theta_vsrc_weight .* phi_vsrc_weight, [8,9]);
        case 'Westervelt'
            dir = Westervelt(pal, fp.theta, fp.phi, 0, 0);
        otherwise
            error('Wrong type!');
    end

    if ip.is_norm_dB
        dir = 20*log10(abs(dir));
        dir = dir - max(dir(:));
    end
end

function dir = Westervelt(pal, theta, phi, theta_vsrc, phi_vsrc)
    gam = cos(theta) .* cos(theta_vsrc) + sin(theta) .* sin(theta_vsrc) ...
        .* cos(phi - phi_vsrc);
    dir = 1i*pal.absorp_coef ./ (pal.ultra_high.num - conj(pal.ultra_low.num) ...
        - pal.audio.num .* gam);
end

function dir = DirectCDM(pal, theta, phi, theta_vsrc, phi_vsrc)
    dir1 = pal.src_low.CalDirectivity(theta_vsrc, phi_vsrc);
    dir2 = pal.src_high.CalDirectivity(theta_vsrc, phi_vsrc);
    dir_westervelt = Westervelt(pal, theta, phi, theta_vsrc, phi_vsrc);
    dir = dir_westervelt .* conj(dir1) .* dir2;
end

function dir = ModifiedCDM(pal, theta, phi, theta_vsrc, phi_vsrc)
    dira = pal.src_audio.CalDirectivity(theta, phi);
    dir = DirectCDM(pal, theta, phi, theta_vsrc, phi_vsrc) .* dira;
end
