% Calculate the 2D field generated by a source with a uniform profile
clear all

% prf = SrcProfile('name', 'uniform');
prf = SrcProfile('name', 'cosine', 'order', 1);
src = LineSrc('prf', prf, 'radius', 0.1, 'freq', 40e3);
m_max = ceil(src.radius .* real(src.wav.num) *1.5);

fp = Point2D('rho', logspace(-2, 1, 5e2).', ...
    'phi', linspace(0, pi, 4.01e2));
fp.Polar2Cart();

tic
prs = LineSrc_CWE(src, fp, 'm_max', m_max, 'is_farfield', false);
toc
spl = PrsToSpl(prs);

%% 2D field
fig = Figure;
pcolor(fp.y.', fp.x.', spl.')
fig.Init;
ylim([-.5,.5]*exp(1)/pi)
xlim([0,4]);
% caxis([90,140]);
xlabel('y(m)');
ylabel('x(m)');
fig.SetColorbarTitle('SPL (dB)')
% fig.ExportTikz('filename', 'CWE/fig/LineSrc_CWE_Test2DUniform_220625B_.tex')

%% Axial field
rho_axis = fp.rho;
spl_axis = spl(:, (length(fp.phi)+1)/2);
fig_axis = Figure;
plot(rho_axis, spl_axis)
fig_axis.hAxes.XScale = 'log';