% =========================================================================
% INTRO
%   - Calculate the radiation generated by a baffled line source using 
%       the cylindrical wave expansion (CWE) method
% -------------------------------------------------------------------------
% INPUT
%   - k: wavenumber
%   - a: half-width (radius) of the source
%   - rho: the polar coodinates 
%   - phi: the azmimuthal coordinates
% DIMEINSION
%   - 1: fp.rho
%   - 2: fp.phi
%   - 3: order
% =========================================================================
function [prs, vel_rho, vel_phi, lag] = LineSrc_CWE(src, fp, varargin)

    ip = inputParser;
    % maximum order
    ip.addParameter('m_max', 100);
    ip.addParameter('src_norm', 'prs', @(x)any(validatestring(x, ...
        {'prs', 'vel', 'surf_vel'})));
    ip.addParameter('is_cal_vel', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('is_cal_lag', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('is_farfield', false)
%     ip.addParameter('array', []);
    ip.parse(varargin{:});
    ip = ip.Results;

    if ip.is_cal_lag
        ip.is_cal_vel = true;
    end

    m = permute((-ip.m_max:ip.m_max).', [3,2,1]);

    % radial component
    [R, R_prime] = LineSrc_CWE_Radial(...
        src, fp.rho, ip.m_max, ...
        'int_num', 5e2, 'is_farfield', ip.is_farfield);

    psi = exp(1i .* m .* fp.phi);

    rho0 = 1.21;
    c0 = 343;
    % normalization scheme
    switch ip.src_norm
        % the pressure is assumed to be 1
        case 'prs'
            ampl = 1;
        % the velocity is assumed to be 1
        case 'vel'
            ampl = rho0 * c0;
        % the surface velocity is assumed to be 1
        case 'surf_vel'
            ampl = rho0 * c0 / (2*a);
    end
    prs = sum(ampl .* R .* psi, 3);
    % res.u_phase = radial_data.u_phase;
    % res.rho_phase = radial_data.rho_phase;

    vel_rho = nan;
    vel_phi = nan;
    lag = nan;

    %% calculate the velocity
    if ~ip.is_cal_vel
        return
    end

    vel_rho = ampl / (1i * rho0 * c0) * sum(neumann .* R_prime .* psi, 3);
    vel_phi = ampl * 1i / (rho0 * c0) * sum(neumann .* m ...
        .* R ./ (k .* rho) .* sin(m .* phi), 3);
    idx_rho = (rho + 0*phi) == 0;
    vel_phi(idx_rho) = 0;

    if ~ip.is_cal_lag
        return
    end
    lag = rho0/2 * (abs(vel_rho).^2 + abs(vel_phi).^2) - abs(prs).^2 / (2*rho0*c0^2);
end
