% Calculate the 2D field generated by a line source 
clear all

% choose a profile
prf = SrcProfile('name', 'uniform');
% prf = SrcProfile('name', 'cosine', 'order', 1);
% prf = SrcProfile('name', 'steerable', 'phi', -15/180*pi);

src = LineSrc('prf', prf, 'radius', 0.1, 'freq', 40e3);

fp = Point2D('rho', [0; logspace(-2, 1, 5e2).'], ...
    'phi', linspace(-pi/2, pi/2, 4.01e2));
fp.Polar2Cart();

tic
prs = LineSrc_CWE(src, fp, 'is_farfield', false);
toc
spl = PrsToSpl(prs);

%% 2D field
fig = Figure;
pcolor(fp.x, fp.y, spl)
fig.Init;
% ylim([-.5,.5]*exp(1)/pi)
ylim([-1,1])
xlim([0,3]);
% caxis([90,140]);
xlabel('x(m)');
ylabel('y(m)');
fig.SetColorbarTitle('SPL (dB)')
% fig.ExportTikz('filename', 'CWE/fig/LineSrc_CWE_Test2DUniform_220625B_.tex')

%% Axial field
rho_axis = fp.rho;
spl_axis = spl(:, (length(fp.phi)+1)/2);
fig_axis = Figure;
plot(rho_axis, spl_axis)
fig_axis.hAxes.XScale = 'log';
