% Calculate the directivity generated by a line source 
clear all

% choose a profile
prf = SrcProfile('name', 'uniform');
% prf = SrcProfile('name', 'cosine', 'order', 1);
prf = SrcProfile('name', 'steerable', 'phi', -15/180*pi);

src = LineSrc('prf', prf, 'radius', 0.1, 'freq', 40e3);

fp = Point2D('rho', 10, ...
    'phi', linspace(-pi/2, pi/2, 4.01e2));
fp.Polar2Cart();

dir_analytic = src.CalDirectivity(fp.phi);
dir_analytic_dB = PrsToSpl(dir_analytic);
dir_analytic_dB = dir_analytic_dB - max(dir_analytic_dB(:));

tic
dir_cwe = LineSrc_CWE(src, fp, 'is_farfield', true);
dir_cwe_dB = PrsToSpl(dir_cwe);
dir_cwe_dB = dir_cwe_dB - max(dir_cwe_dB(:));
toc

%% plot results
fig = Figure;
plot(fp.phi/pi*180, dir_analytic_dB);
hold on
plot(fp.phi/pi*180, dir_cwe_dB, '--');
fig.Init;
legend({'Analytical results', 'CWE'})
