% =========================================================================
% INTRO
%   - Calculate the radiation generated by a baffled line source using 
%       the cylindrical wave expansion (CWE) method
% -------------------------------------------------------------------------
% INPUT
%   - src: data of the circular source 
%   - fp.rho, fp.phi: the radial and azimuthal coordinates of the field 
%       points
% DIMEINSION
%   - 1: fp.rho
%   - 2: fp.phi
%   - 3: order
% =========================================================================
function [prs, vel, lag] = LineSrc_CWE(src, fp, varargin)

    ip = inputParser;
    % maximum order
    ip.addParameter('m_max', ceil(src.radius*real(src.wav.num)*1.2), ...
        @(x)validateattributes(x, {'numeric'}, {'scalar', '>', 0}));
    ip.addParameter('src_norm', 'prs', @(x)any(validatestring(x, ...
        {'prs', 'vel', 'surf_vel'})));
    ip.addParameter('is_cal_vel', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    % Calculate Lagrangian density
    ip.addParameter('is_cal_lag', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('is_farfield', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('int_num', 2e2, @(x)validateattributes(x, {'numeric'}, {'scalar', '>=', 2}));
    ip.parse(varargin{:});
    ip = ip.Results;

    if ip.is_cal_lag
        ip.is_cal_vel = true;
    end

    m = permute((-ip.m_max:ip.m_max).', [3,2,1]);

    % radial component
    [R, R_prime] = LineSrc_CWE_Radial(...
        src, fp.rho, ip.m_max, ...
        'int_num', ip.int_num, ...
        'is_farfield', ip.is_farfield);

    psi = exp(1i .* m .* fp.phi);

    rho0 = 1.21;
    c0 = 343;
    % normalization scheme
    switch ip.src_norm
        % the pressure is assumed to be 1
        case 'prs'
            ampl = 1;
        % the velocity is assumed to be 1
        case 'vel'
            ampl = rho0 * c0;
        % the surface velocity is assumed to be 1
        case 'surf_vel'
            ampl = rho0 * c0 / (2*a);
    end
    prs = sum(ampl .* R .* psi, 3);
    % res.u_phase = radial_data.u_phase;
    % res.rho_phase = radial_data.rho_phase;

    vel.rho = nan;
    vel.phi = nan;
    lag = nan;

    %% calculate the velocity
    if ~ip.is_cal_vel
        return
    end

    vel.rho = ampl / (1i * rho0 * c0) * sum(neumann .* R_prime .* psi, 3);
    vel.phi = ampl * 1i / (rho0 * c0) * sum(neumann .* m ...
        .* R ./ (k .* rho) .* sin(m .* phi), 3);
    idx_rho = (rho + 0*phi) == 0;
    vel.phi(idx_rho) = 0;

    if ~ip.is_cal_lag
        return
    end
    lag = rho0/2 * (abs(vel.rho).^2 + abs(vel.phi).^2) - abs(prs).^2 / (2*rho0*c0^2);
end
