% =========================================================================
% INTRO
%   - Calculate the radial component for audio sound when calculating
%       the sound pressure generated by a line source in 2D problem
% -------------------------------------------------------------------------
% INPUT
% DIMENSION
%   - 1, 2: rho 
%   - 3: ma
%   - 4: m1
%   - 5: rho_vsrc
% =========================================================================
function radial = PalLineSrc_CWE_Radial1(...
    k1, k2, ka, ...
    a, rho, varargin)

    validateattributes(k1, {'numeric'}, {'scalar'});
    validateattributes(k2, {'numeric'}, {'scalar'});
    validateattributes(ka, {'numeric'}, {'scalar'});
    validateattributes(a, {'numeric'}, {'scalar', '>=', 0});
    validateattributes(rho, {'numeric'}, {'size', [nan,nan,1], '>=', 0});

    ip = inputParser;
    % number of points for the numerical integration
    ip.addParameter('int_num', 3e2, @(x)validateattributes(x, {'numeric'}, {'scalar', '>=', 2}));
    ip.addParameter('profile', 'uniform', @(x)any(validatestring(x, {'uniform', 'steerable'})));
    ip.addParameter('steer_angle', nan);
    % ip.addParameter('steer_angle_lower', pi/2);
    % ip.addParameter('steer_angle_upper', pi/2);
    ip.addParameter('is_farfield', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('ma_max', 3e1);
    ip.addParameter('m1_max', 1e2);
    parse(ip, varargin{:});
    ip = ip.Results;

    [rho_vsrc, weight] = GaussLegendreQuadParam(ip.int_num, 0, a);
    rho_vsrc = permute(rho_vsrc, [5,2,3,4,1]);
    weight = permute(weight, [5,2,3,4,1]);

    ma = permute((-ip.ma_max:ip.ma_max).', [3,2,1]);
    m1 = permute((-ip.m1_max:ip.m1_max).', [4,2,3,1]);

    % rho = permute(rho, [3,2,1,4,5]);
    R_m1 = 0 * rho_vsrc .* m1;
    R_m1(:,:,:,ip.m1_max+1:end,:) = permute(...
        LineSrc_CWE_Radial(...
        ip.m1_max, k1, a, ...
        permute(rho_vsrc, [5,2,3,4,1]), ...
        'int_num', 3e2,...
        'steer_angle', ip.steer_angle,...
        'profile', ip.profile), [5,2,3,4,1]);
    R_m1(:,:,:,1:ip.m1_max,:) = R_m1(:,:,:,end:-1:ip.m1_max+2,:);
    
    R_m2 = 0 * rho_vsrc .* m1 .* ma;
    R_m2_buf = permute(...
        LineSrc_CWE_Radial(...
        ip.m1_max + ip.ma_max, k2, a, ...
        permute(rho_vsrc, [5,2,3,4,1]), ...
        'int_num', 3e2,...
        'steer_angle', ip.steer_angle,...
        'profile', ip.profile), [5,2,3,4,1]);
    for i = -ip.ma_max : ip.ma_max
        for j = -ip.m1_max : ip.m1_max
            R_m2(1,1,i+ip.ma_max+1,j+ip.m1_max+1,:) ...
                = R_m2_buf(1,1,abs(i+j)+1,1,:);
        end
    end

    if ~ip.is_farfield
        JH = 0 * ma .* rho_vsrc .* rho;
        [JH_prototype, JH_exp] = BesselJHankelProduct(...
            ip.ma_max,...
            ka * min(rho_vsrc, permute(rho, [3,2,1])), ...
            ka * max(rho_vsrc, permute(rho, [3,2,1])));
        JH_prototype = JH_prototype .* 10.^JH_exp;
        JH(:, 1, ip.ma_max+1:end,1,:) = permute(JH_prototype, [3,2,1,4,5]);
        JH(:, 1, 1:ip.ma_max,1,:) = JH(:, 1, end:-1:ip.ma_max+2,1,:);
    else
        % inverse-law far field
        ka = real(ka);
        J = 0 * ma .* rho_vsrc;
        % dimension: ma; rho_vsrc
        J_prototype = exp(BesselJLog(ip.ma_max, ka*rho_vsrc(:).'));
        % dimension: 1; 1; ma; 1; rho_vsrc
        J_prototype = permute(permute(J_prototype, [3,2,1]), [1,5,3,4,2]);
        J(1, 1, ip.ma_max+1:end,1,:) = J_prototype;
        J(1, 1, 1:ip.ma_max,1,:) = (-1).^permute((ip.ma_max:-1:1).', [3,2,1])...
            .* J(1, 1, end:-1:ip.ma_max+2, 1, :);
        H = sqrt(2/pi/ka./rho) .* exp(1i*(ka.*rho- ma.*pi/2 - pi/4));
        JH = J .* H;
    end

    radial = sum(sum(conj(R_m1) .* R_m2 .* JH .* ka^2 .* rho_vsrc .* weight, 5), 4);
end
