% =========================================================================
% INTRO
%   - Calculate the radial component for audio sound when calculating
%       the sound pressure generated by a line source in 2D problem
%   - Farfield solution
% -------------------------------------------------------------------------
% INPUT
% DIMENSION
%   - 1, 2: rho 
%   - 3: ma
%   - 4: m1
%   - 5: integration
% =========================================================================
function R = PalLineSrc_CWE_RadialFar(...
    pal, rho, ma_max, m1_max, varargin)

    ip = inputParser;
    % number of points for the numerical integration
    ip.addParameter('int_num', 2e3, @(x)validateattributes(x, {'numeric'}, {'scalar', '>=', 2}));
    parse(ip, varargin{:});
    ip = ip.Results;

    a = pal.src_low.radius;

    R = 0;
%     rho_part = [0; 1; 5; 10; 20; 50; 100; 200; 1e3; inf]*a;
    rho_part = [0; 1; 10; 100; 1e3; inf]*a;
    % rho_part = [0; .5; 1.1; 2; 5; 7; 10; 12; 15; 20; 25; 100; 1e3; inf]*a;
    for i = 1:length(rho_part)-1
        R = R + PalLineSrc_CWE_RadialJ(...
            pal, ma_max, m1_max, rho_part(i), rho_part(i+1), rho, ...
            'is_farfield', true, 'int_num', ip.int_num);
    end

end
