% =========================================================================
% INTRO
%   - Calculate the radial component for audio sound when calculating
%       the sound pressure generated by a line source in 2D problem
% -------------------------------------------------------------------------
% INPUT
% DIMENSION
%   - 1: rho 
%   - 2: phi (holder)
%   - 3: ma
%   - 4: m1
%   - 5: integration
% =========================================================================
function R = PalLineSrc_CWE_Radial(...
    pal, rho, ma_max, m1_max, varargin)

    ip = inputParser;
    % number of points for the numerical integration
    ip.addParameter('is_farfield', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    parse(ip, varargin{:});
    ip = ip.Results;

    a = pal.src_low.radius;
    ma = permute((-ma_max:ma_max).', [3,2,1]);
    % m1 = permute((-m1_max:m1_max).', [4,2,3,1]);

    if ip.is_farfield
        % the partition for r can be modified per specific parameters
        rho_part = [0; 1; 2; 5; 10; 20; 50; 100; 200; 1e3; inf]*a;
%         rho_part = [0; 0.3; .5; 1; 1.5; 2; 5; 10; 15; 20; 30; 40; 50; 100; 200; 500; 1e3; inf]*a;
%         r_part = [0; 0.3*a; 0.5*a; 0.9*a; a; .3; .5; 1; 1.5; 2; 2.5; 3;3.5; 4; 4.5;5;
%             6; 7; 8; 9; 10; 12; 15; 17; 20; 25; 30; 40; 50; 52; 55; 70; 100; 150; 200; 300; 500; inf];
        R = 0;
        for i = 1:length(rho_part)-1
            R = R + PalLineSrc_CWE_RadialInt(...
                pal, ma_max, m1_max, rho_part(i), rho_part(i+1), rho, 'J', ...
                'is_farfield', ip.is_farfield, 'int_num', 5e2);
        end
    else
        % origin point
        idx_origin = rho == 0;
        rho_origin = rho(idx_origin);
        % interior points
        idx_int = (rho > 0) & (rho < a);
        rho_int = rho(idx_int);
        % exterior points
        idx_ext = rho >= a;
        rho_ext = rho(idx_ext);

        % radial components
        R = 0 * rho .* ma;
    
        % process origin points
        if ~isempty(rho_origin)
            R(idx_origin, 1, :) ...
                = PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, 0, a, 0, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a, a+2, 0, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a+2, a+5, 0, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a+5, inf, 0, 'H');
        end
        % process interior points
        if ~isempty(rho_int)
            R(idx_int, 1, :) ...
                = PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, 0, rho_int, rho_int, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_int, a, rho_int, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a, a+2, rho_int, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a+2, a+5, rho_int, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a+5, inf, rho_int, 'H');
        end
        % process exterior points
        if ~isempty(rho_ext)
            % R(idx_ext, 1, :) ...
                % = PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, 0, a, rho_ext, 'J') ...
                % + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a, rho_ext, rho_ext, 'J') ...
                % + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext, rho_ext+2, rho_ext, 'H') ...
                % + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext+2, rho_ext+5, rho_ext, 'H') ...
                % + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext+5, inf, rho_ext, 'H');
            R(idx_ext, 1, :) ...
                = PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, 0, a, rho_ext, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, a, rho_ext/20, rho_ext, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext/20, rho_ext/10, rho_ext, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext/10, rho_ext/5, rho_ext, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext/5, rho_ext/2, rho_ext, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext/2, rho_ext, rho_ext, 'J') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext, rho_ext+2, rho_ext, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext+2, rho_ext+5, rho_ext, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext+5, rho_ext+10, rho_ext, 'H') ...
                + PalLineSrc_CWE_RadialInt(pal, ma_max, m1_max, rho_ext+10, inf, rho_ext, 'H');
        end
    end
end
