% =========================================================================
% INTRO
%   - Calcualte the radiation generated by a PAL field using the CWE method 
%   - 2D Problem
% -------------------------------------------------------------------------
% INPUT
%   -
% DIMENSION
%   - 1: fp.rho
% % - 2: fp.phi
%   - 3: ma
% =========================================================================
function [prs, prs_cum, prs_m] = PalLineSrc_CWE(pal, fp, varargin)

    ip = inputParser;
%     ip.addParameter('profile', 'uniform', @(x)any(validatestring(x, {'uniform', 'steerable'})));
    % ip.addParameter('steer_angle_lower', pi/2);
    % ip.addParameter('steer_angle_upper', pi/2);
%     ip.addParameter('steer_angle', nan, @(x)validateattributes(x, {'numeric'}, {'size', [nan, 1]}));
    % ip.addParameter('is_discrete', 0);
    % ip.addParameter('discrete_size', 0.01);
    % ip.addParameter('is_effective', 0);
    % ip.addParameter('effective_size', 0.01);
    ip.addParameter('ma_max', 3e1);
    ip.addParameter('m1_max', ceil(1.5*real(pal.ultra_low.num * pal.src_low.radius)));
    ip.addParameter('src_norm', 'vel', @(x)any(validatestring(x, {'vel', 'surf_vel', 'prs'})));
    ip.addParameter('eqn', 'Westervelt', @(x)any(validatestring(x, {'Westervelt', 'WesterveltCorrection'})));
    ip.addParameter('is_farfield', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('array', []);
    ip.parse(varargin{:});
    ip = ip.Results;

    k1 = pal.ultra_low.num;
    k2 = pal.ultra_high.num;
    ka = pal.audio.num;
    a = pal.src_low.radius;
    
    ma = permute((-ip.ma_max:ip.ma_max).', [3,2,1]);

    psi = exp(1i*ma.*fp.phi);

    %% calcualte the radial component
    if ip.is_farfield
        radial = ...
            PalLineSrc_CWE_RadialFar(...
            pal, fp.rho, ip.ma_max, ip.m1_max);
    else
        radial = ...
            PalLineSrc_CWE_Radial(...
            k1, k2, ka, ...
            a, fp.rho, ...
            'ma_max', ip.ma_max, ...
            'm1_max', ip.m1_max, ...
            'is_farfield', ip.is_farfield, ...
            'profile', ip.profile,...
            'steer_angle', ip.steer_angle, ...
            'array', ip.array);
    end
    %% calculate the results 
    beta = 1.2;
    rho0 = 1.21;
    c0 = 343;
    ampl = beta * pi * rho0 / 2 / 1i;
    switch ip.src_norm
        case 'vel'
            ;
        case 'prs'
            ampl = ampl / (rho0 * c0)^2;
        case 'surf_vel'
            ampl = ampl / (2*a)^2;
    end
    prs_m = ampl .* radial .* psi;
    prs = sum(prs_m, 3);

    prs_cum = nan;
    if ip.is_farfield
        return
    end
    switch ip.eqn
        case 'WesterveltCorrection'
            [prs1, vel_rho1, vel_phi1] = LineSrc_CWE(k1, a, ...
                fp.rho, fp.phi, ...
                'is_cal_vel', true, ...
                'src_norm', ip.src_norm);
            [prs2, vel_rho2, vel_phi2] = LineSrc_CWE(k2, a, ...
                fp.rho, fp.phi, ...
                'is_cal_vel', true, ...
                'src_norm', ip.src_norm);
            lag = rho0/2.*(conj(vel_rho1) .* vel_rho2 + conj(vel_phi1) .* vel_phi2) ...
                - (real(k1)/real(k2) + real(k2)/real(k1) - 1) ...
                .* conj(prs1) .* prs2 / (2 * rho0 * c0^2);
            prs_cum = prs;
            prs = prs - lag;
    end
end
