% =========================================================================
% INTRO
%   - Calculate the radial component for audio sound when calculating
%       the sound pressure generated by a line source in 2D problem
% -------------------------------------------------------------------------
% INPUT
% DIMENSION
%   - 1, 2: rho 
%   - 3: ma
%   - 4: m1
%   - 5: rho_vsrc
% =========================================================================
function radial = PalLineSrc_CWE_RadialH2(...
    k1, k2, ka, ...
    a, m1, ma, varargin)

    validateattributes(k1, {'numeric'}, {'scalar'});
    validateattributes(k2, {'numeric'}, {'scalar'});
    validateattributes(ka, {'numeric'}, {'scalar'});
    validateattributes(a, {'numeric'}, {'scalar', '>=', 0});

    ip = inputParser;
    % number of points for the numerical integration
    ip.addParameter('int_num', 5e2, @(x)validateattributes(x, {'numeric'}, {'scalar', '>=', 2}));
    ip.addParameter('profile', 'uniform', @(x)any(validatestring(x, {'uniform', 'steerable'})));
    ip.addParameter('steer_angle', [pi/4;pi/2]);
    % ip.addParameter('steer_angle_lower', pi/2);
    % ip.addParameter('steer_angle_upper', pi/2);
    ip.addParameter('is_farfield', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('ma_max', nan);
    ip.addParameter('m1_max', nan);
    ip.addParameter('int_method', 'gauss');
    ip.addParameter('is_log', false)
    parse(ip, varargin{:});
    ip = ip.Results;

    if ~isnan(ip.ma_max) && ~isnan(ip.m1_max)
        ma = permute((-ip.ma_max:ip.ma_max).', [3,2,1]);
        m1 = permute((-ip.m1_max:ip.m1_max).', [4,2,3,1]);
    end
    m2 = m1+ma;

    alpha = imag(k1) + imag(k2);
    switch ip.int_method
        case 'gauss'
%             [rho_vsrc, weight] = GaussLegendreQuadParam(ip.int_num, a, inf);
%             rho_vsrc = permute(rho_vsrc, [5,2,3,4,1]);
%             weight = permute(weight, [5,2,3,4,1]);
%             weight = weight .* exp(-(imag(k1)+imag(k2)).*rho_vsrc);
%             radial = sum(Fun1(k1, k2, ka, m1, m2, ma, rho_vsrc) ...
%                 .* ka^2 .* rho_vsrc .* weight, 5);
            radial = GaussLegendreQuad(@(rho_vsrc) ...
                FunLog(k1, k2, ka, m1, m2, ma, rho_vsrc), ...
                a, inf, 'int_num', ip.int_num, 'is_log', true, 'dim', 5);
            if ~ip.is_log
                radial = exp(radial);
            end
        case 'matlab'
           radial = integral(@(rho_vsrc) Fun1(k1, k2, ka, ...
              m1, m2, ma, rho_vsrc) ...
            .* exp(-alpha.*rho_vsrc) ...
            .* ka^2 .* rho_vsrc, a, inf, 'ArrayValued', true);
    end
end

function res = Fun1(k1, k2, ka, m1, m2, ma, rho_vsrc)
    res = conj(HankelH_Matlab(m1, k1*conj(rho_vsrc), 'kind', 1, 'scaled', true)) ...
        .* HankelH_Matlab(m2, k2*rho_vsrc, 'kind', 1, 'scaled', true) ...
        .* HankelH_Matlab(ma, ka*rho_vsrc, 'kind', 2, 'scaled', true);
end

% Calculated based on the self written codes
function res = FunLog(k1, k2, ka, m1, m2, ma, rho_vsrc)
    alpha = imag(k1) + imag(k2);
    H_m1 = HankelHScaled(m1(:), k1*conj(rho_vsrc), 'is_log', true);
    H_m2 = HankelHScaled(m2(:), k2*rho_vsrc, 'is_log', true);
    H_ma = HankelHScaled(ma(:), ka*rho_vsrc, 'is_log', true, 'kind', 2);
    IsInvalid(H_m1, 'var_name', 'H_m1');
    IsInvalid(H_m2, 'var_name', 'H_m2');
    IsInvalid(H_ma, 'var_name', 'H_ma');
    H_m1 = reshape(H_m1, size(m1 .* rho_vsrc));
    H_m2 = reshape(H_m2, size(m2 .* rho_vsrc));
    H_ma = reshape(H_ma, size(ma .* rho_vsrc));
    res = (conj(H_m1) + H_m2 + H_ma - alpha.*rho_vsrc)...
        + log(ka^2 .* rho_vsrc);
end
