% =========================================================================
% INTRO
%   - Calculate the type H radial component for audio sound when calculating
%       the sound pressure generated by a line source in 2D problem
% -------------------------------------------------------------------------
% INPUT
% DIMENSION
%   - 1, 2: rho 
%   - 3: ma
%   - 4: m1
%   - 5: rho_vsrc
% =========================================================================
function radial = PalLineSrc_CWE_RadialH(...
    k1, k2, ka, a, m1, ma, ...
    varargin)

    validateattributes(k1, {'numeric'}, {'scalar'});
    validateattributes(k2, {'numeric'}, {'scalar'});
    validateattributes(ka, {'numeric'}, {'scalar'});
    validateattributes(a, {'numeric'}, {'scalar', '>=', 0});
    validateattributes(ma, {'numeric'}, {'size', [1,1,nan]});
    validateattributes(m1, {'numeric'}, {'size', [1,1,1,nan]});

    ip = inputParser;
    % number of points for the numerical integration
    ip.addParameter('int_num', 5e2, @(x)validateattributes(x, {'numeric'}, {'scalar', '>=', 2}));
    ip.addParameter('profile', 'uniform', @(x)any(validatestring(x, {'uniform', 'steerable'})));
    ip.addParameter('steer_angle', [pi/4;pi/2]);
    % ip.addParameter('steer_angle_lower', pi/2);
    % ip.addParameter('steer_angle_upper', pi/2);
    ip.addParameter('is_farfield', false, @(x)validateattributes(x, {'logical'}, {'scalar'}));
    ip.addParameter('int_method', 'deepest');
    % suggest to use log to avoid overflow
    ip.addParameter('is_log', false)
    ip.addParameter('ma_max', nan);
    ip.addParameter('m1_max', nan);
    parse(ip, varargin{:});
    ip = ip.Results;

    if ~isnan(ip.ma_max) && ~isnan(ip.m1_max)
        ma = permute((-ip.ma_max:ip.ma_max).', [3,2,1]);
        m1 = permute((-ip.m1_max:ip.m1_max).', [4,2,3,1]);
    end
    m2 = m1+ma;
%     alpha = imag(k1) + imag(k2);

    switch ip.int_method
        % directly using Gauss quadrature
        case 'direct_gauss'
            radial = GaussLegendreQuad(@(rho_vsrc) ...
                FunLog1(k1, k2, ka, m1, m2, ma, rho_vsrc), ...
                a, inf, 'int_num', ip.int_num, 'is_log', true, ...
                'dim', 5);
            if ~ip.is_log
                radial = exp(radial);
            end
        % deepest descent method
        case 'deepest'
            radial = GaussLegendreQuad(@(rho_vsrc) ...
                FunLog2(k1, k2, ka, m1, m2, ma, a, rho_vsrc), ...
                0, inf, 'int_num', ip.int_num, 'is_log', true, ...
                'dim', 5);
            if ~ip.is_log
                radial = exp(radial);
            end
        % hybrid: accurate and efficient
        case 'hybrid'
            ma0 = 40;
            idx_deepest = abs(ma) <= ma0;
            idx_gauss = abs(ma) > ma0;
            radial = 0 * m1 .* ma;
            if sum(idx_deepest(:))>0
                radial(:,:,idx_deepest,:) = GaussLegendreQuad(@(rho_vsrc) ...
                    FunLog2(k1, k2, ka, m1, m2(:,:,idx_deepest,:), ma(idx_deepest), a, rho_vsrc), ...
                    0, inf, 'int_num', ip.int_num, 'is_log', true, ...
                'dim', 5);
            end
            if sum(idx_gauss(:))>0
                radial(:,:,idx_gauss,:) = GaussLegendreQuad(@(rho_vsrc) ...
                    FunLog1(k1, k2, ka, m1, m2(:,:,idx_gauss,:), ma(idx_gauss), rho_vsrc), ...
                    a, inf, 'int_num', ip.int_num, 'is_log', true, ...
                'dim', 5);
            end
            if ~ip.is_log
                radial = exp(radial);
            end
        % directly using the integral function provided by MATLAB
        case 'matlab'
             radial = integral(@(rho_vsrc) Fun2(k1, k2, ka, ...
                m1, m2, ma, rho_vsrc), a, inf, 'ArrayValued', true);
        otherwise
            error('Wrong int_method!')
    end
end

function res = FunLog1(k1, k2, ka, m1, m2, ma, rho_vsrc)
    alpha = imag(k1+k2);
    H_m1 = HankelHScaled(m1(:), k1*conj(rho_vsrc), 'is_log', true);
    H_m2 = HankelHScaled(m2(:), k2*rho_vsrc, 'is_log', true);
    H_ma = HankelHScaled(ma(:), ka*rho_vsrc, 'is_log', true);
    IsInvalid(H_m1, 'var_name', 'H_m1');
    IsInvalid(H_m2, 'var_name', 'H_m2');
    IsInvalid(H_ma, 'var_name', 'H_ma');
    H_m1 = reshape(H_m1, size(m1 .* rho_vsrc));
    H_m2 = reshape(H_m2, size(m2 .* rho_vsrc));
    H_ma = reshape(H_ma, size(ma .* rho_vsrc));
    res = (conj(H_m1) + H_m2 + H_ma + 2*1i*ka*rho_vsrc-alpha.*rho_vsrc)...
        + log(ka^2 .* rho_vsrc);
end

function res = FunLog2(k1, k2, ka, m1, m2, ma, a, rho_vsrc)
    alpha = imag(k1+k2);
    K = (2*1i*ka + alpha) ./ (4*ka.^2 + alpha.^2);
    rho_vsrc = K.*rho_vsrc+a;
    res = FunLog1(k1, k2, ka, m1, m2, ma, rho_vsrc) + log(K);
end

function res = Fun1(k1, k2, ka, m1, m2, ma, rho_vsrc)
%     res = conj(HankelH_Matlab(m1, k1*conj(rho_vsrc), 'kind', 1, 'scaled', true)) ...
%         .* HankelH_Matlab(m2, k2*rho_vsrc, 'kind', 1, 'scaled', true) ...
%         .* HankelH_Matlab(ma, ka*rho_vsrc, 'kind', 1, 'scaled', true);
    alpha = imag(k1+k2);
    H_m1 = HankelHScaled(m1(:), k1*conj(rho_vsrc), 'is_log', true);
    H_m2 = HankelHScaled(m2(:), k2*rho_vsrc, 'is_log', true);
    H_ma = HankelHScaled(ma(:), ka*rho_vsrc, 'is_log', true);
    H_m1 = reshape(H_m1, size(m1 .* rho_vsrc));
    H_m2 = reshape(H_m2, size(m2 .* rho_vsrc));
    H_ma = reshape(H_ma, size(ma .* rho_vsrc));
    res = exp(conj(H_m1) + H_m2 + H_ma + 2*1i*ka*rho_vsrc-alpha.*rho_vsrc)...
        .* ka^2 .* rho_vsrc;

%     res = conj(HankelH_Matlab(m1, k1*conj(rho_vsrc), 'kind', 1, 'scaled', true)) ...
%         .* HankelH_Matlab(m2, k2*rho_vsrc, 'kind', 1, 'scaled', true) ...
%         .* HankelH_Matlab(ma, ka*rho_vsrc, 'kind', 1, 'scaled', true) ...
%         .* exp(2*1i*ka*rho_vsrc-alpha.*rho_vsrc) .* ka^2 .* rho_vsrc;
%     res = conj(HankelHScale(m1, k1*conj(rho_vsrc))) ...
%         .* HankelH_Matlab(m2, k2*rho_vsrc, 'kind', 1, 'scaled', true) ...
%         .* HankelH_Matlab(ma, ka*rho_vsrc, 'kind', 1, 'scaled', true);
end

function res = Fun2(k1, k2, ka, m1, m2, ma, rho_vsrc)
%     res = conj(HankelH_Matlab(m1, k1*conj(rho_vsrc), 'kind', 1, 'scaled', true)) ...
%         .* HankelH_Matlab(m2, k2*rho_vsrc, 'kind', 1, 'scaled', true) ...
%         .* HankelH_Matlab(ma, ka*rho_vsrc, 'kind', 1, 'scaled', true);
    alpha = imag(k1+k2);
%     H_m1 = HankelHScaled(m1(:), k1*conj(rho_vsrc), 'is_log', true);
%     H_m2 = HankelHScaled(m2(:), k2*rho_vsrc, 'is_log', true);
%     H_ma = HankelHScaled(ma(:), ka*rho_vsrc, 'is_log', true);
%     H_m1 = reshape(H_m1, size(m1 .* rho_vsrc));
%     H_m2 = reshape(H_m2, size(m2 .* rho_vsrc));
%     H_ma = reshape(H_ma, size(ma .* rho_vsrc));
%     res = exp(conj(H_m1) + H_m2 + H_ma)...
%         .* exp(2*1i*ka*rho_vsrc-alpha.*rho_vsrc) .* ka^2 .* rho_vsrc;

    m1_col = m1 + 0*ma;
    m1_col = m1_col(:);
    m2_col = m2(:);
    ma_col = ma + 0*m1;
    ma_col = ma_col(:);

    res = conj(HankelH_Matlab(m1_col, k1*conj(rho_vsrc), 'kind', 1, 'scaled', true)) ...
        .* HankelH_Matlab(m2_col, k2*rho_vsrc, 'kind', 1, 'scaled', true) ...
        .* HankelH_Matlab(ma_col, ka*rho_vsrc, 'kind', 1, 'scaled', true) ...
        .* exp(2*1i*ka*rho_vsrc-alpha.*rho_vsrc) .* ka^2 .* rho_vsrc;
    res = reshape(res, size(m2));
end

