% =========================================================================
% INTRO
%   - Calculate the audio sound pressure generated by a line piston PAL
%   - Direct method: direct numerical integrations 
% -------------------------------------------------------------------------
% INPUT
%   - ka, the wavenumber of the audio sound
%   - k1, the wavenumber of the ultrasound at the lower frequency
%   - k2, the wavenumber of the ultrasound at the higher frequency
%   - a, the half width of the radiation surface
%   - x, the x-coordinate of the field points
%   - y, the y-coordinate of the field points
% -------------------------------------------------------------------------
% OUTPUT
%   - prs, the audio sound pressure
% =========================================================================
function prs = PalLinePiston_Direct(ka, k1, k2, a, x, y, varargin)

    validateattributes(ka, {'numeric'}, {'scalar'});
    validateattributes(k1, {'numeric'}, {'scalar'});
    validateattributes(k2, {'numeric'}, {'scalar'});
    validateattributes(a, {'numeric'}, {'scalar'});

    if real(k1) > real(k2)
        error('k1 must be the wavenumber of the ultrasound at lower frequency!.\n');
    end

    beta = 1.2;
    rho0 = 1.21;
    c0 = 343;
    prs = integral2(@(rhov, phiv) Integrand(ka, k1, k2, a, x, y, rhov, phiv), ...
        0, Inf, 0, 2*pi, ...
        'AbsTol', 0, 'RelTol', 1e-3) * beta/(4*1i*rho0*c0^2);
%     prs = integral(@(phiv) integral(@(rhov) ...
%         Integrand(ka, k1, k2, a, x, y, rhov, phiv), ...
%         0, Inf, 'AbsTol', 0, 'RelTol', 1e-3, 'ArrayValued', true), ...
%         0, 2*pi, 'AbsTol', 0, 'RelTol', 1e-3, 'ArrayValued', true) ...
%         * beta/(4*1i*rho0*c0^2);
end

function int = Integrand(ka, k1, k2, a, x, y, rhov, phiv)
    prs1 = LineSrc_Direct(k1, a, rhov.*cos(phiv)+x, rhov.*sin(phiv)+y);
    prs2 = LineSrc_Direct(k2, a, rhov.*cos(phiv)+x, rhov.*sin(phiv)+y);
    int = conj(prs1) .* prs2 .* besselh(0, ka .* rhov) .* rhov;
end
